from contextlib import contextmanager
import itertools
import operator
import time
from functools import reduce
from operator import mul

import sympy as sp

from utility_general import find_zero_vars, prune_singletons, vector_variable
from utility_roots import evaluate_character, evaluate_cocharacter


# This module is an external, factored version of the brute-force Weyl element
# search that currently lives inside pinned_group.fit_weyl_group_elements().
#
# It deliberately does not modify pinned_group.py.  The only dependency on the
# pinned_group class is through the fitted group object G: root systems, root
# subgroup maps, group constraints, torus helpers, and the final fields where
# Weyl data are installed.
#
# The goal is readability and future experimentation, not a new algorithm.
# Function names below correspond to the main phases of the original method:
# symbolic initialization, root-conjugation pruning, torus-normalizer pruning,
# candidate-value construction, finite candidate enumeration, and installation.
#
# Original algorithm outline:
#
#   1. Initialize a fully symbolic n x n matrix with entries w_ij.
#
#   2. Use the equation
#
#          w_alpha * x_beta(u) * w_alpha^(-1)
#              = x_{sigma_alpha(beta)}(v)
#
#      for beta ranging over the root system to eliminate some variables w_ij.
#      In practice, avoid inverting the symbolic matrix and use
#
#          w_alpha * x_beta(u)
#              = x_{sigma_alpha(beta)}(v) * w_alpha.
#
#   3. Use the equation
#
#          w_alpha * t * w_alpha^(-1) = s
#
#      saying that w_alpha normalizes the torus.  Again, avoid symbolic
#      inversion and use
#
#          w_alpha * t = s * w_alpha.
#
#   4. If the group is a special unitary group over a quadratic extension
#      L/k with primitive element p_e, replace each remaining entry w_ij by
#
#          x_ij + p_e * y_ij.
#
#   5. At this point, the Weyl matrix should be sparse.  Enumerate small
#      candidate values, usually 0, +/-1, and in the quadratic case values
#      involving p_e.  Remove 0 as a candidate when a variable is the only
#      possible nonzero entry in its row or column.
#
#   6. Brute-force search the remaining candidates, trying assignments with
#      exactly n nonzero entries, where n is the matrix size.
#
#   7. After a group-theoretic solution is found, test whether its support
#      pattern is compatible with the subgroup generated by x_alpha and
#      x_{-alpha}.  Accept the first candidate that passes.
#
# This factored file also has an experimental monomial-support enumeration
# stage.  It keeps the same finite value search, but replaces unrestricted
# support combinations by entry supports with one nonzero position in each row
# and column, as expected for representatives normalizing a diagonal torus.


def fit_torus_reflection_map(G, display=True, counters=None):
    """Install the torus reflection map s_alpha on G.

    Input:
        G: a pinned_group-like object with root_system, torus helpers, and
            coroot data already fitted.
        display: whether to print progress text.
        counters: optional dict from new_weyl_factored_counters().
    Output:
        None. Mutates G by assigning G.torus_reflection_map.
    """
    if display:
        print("Fitting torus reflections (s_α)")

    with timed_stage(counters, "time_torus_reflections_seconds"):
        def torus_refl_map(alpha, t):
            assert G.root_system.is_root(alpha), "Can only perform torus reflection with a root from the root system"
            assert G.is_torus_element(t), "Can only perform torus reflection on a torus element"
            alpha_of_t = evaluate_character(alpha, t)
            alpha_of_t_inverse = alpha_of_t**(-1)
            alpha_check = G.root_system.coroot_dict[alpha]
            alpha_check_of_alpha_of_t_inverse = evaluate_cocharacter(alpha_check, alpha_of_t_inverse)
            assert G.is_torus_element(alpha_check_of_alpha_of_t_inverse), "Cocharacter must return torus element"
            return t * alpha_check_of_alpha_of_t_inverse

        G.torus_reflection_map = torus_refl_map


def initialize_symbolic_weyl_matrix(G, counters=None):
    """Create the symbolic Weyl matrix used at the start of the search.

    Input:
        G: a pinned_group-like object with matrix_size.
        counters: optional dict from new_weyl_factored_counters().
    Output:
        A pair (w_alpha, w_vars), where w_alpha is the full symbolic
        matrix (w_ij), and w_vars is the set of all symbolic entries.
    """
    with timed_stage(counters, "time_symbolic_initialization_seconds"):
        w_alpha = sp.Matrix(
            G.matrix_size,
            G.matrix_size,
            lambda i, j: sp.symbols(f'w_{i}_{j}'),
        )
    return w_alpha, w_alpha.free_symbols


def get_generic_weyl_context(G, counters=None):
    """Collect generic torus elements and generic nonzero parameters.

    Input:
        G: a pinned_group-like object with generic_torus_element, optional
            non_variables, and optional form data.
        counters: optional dict from new_weyl_factored_counters().
    Output:
        A tuple (t, s, generic_vars).  Here t and s are generic torus
        elements, and generic_vars is the set of symbols treated as generic
        when zero-forcing equations are analyzed.
    """
    with timed_stage(counters, "time_generic_context_seconds"):
        t = G.generic_torus_element('t')
        s = G.generic_torus_element('s')
        generic_vars = t.free_symbols
        if G.non_variables is not None:
            generic_vars = generic_vars.union(G.non_variables)
        if G.form is not None:
            generic_vars = generic_vars.union(G.form.anisotropic_vector.free_symbols)
    return t, s, generic_vars


def get_cached_root_data(G, alpha, beta, root_data_cache, counters=None):
    """Return reflected root data, using a caller-provided cache.

    Input:
        G: a pinned_group-like object with root_system and root_space_dimension.
        alpha: the root defining the reflection hyperplane.
        beta: the root being reflected.
        root_data_cache: dict keyed by (alpha, beta).
        counters: optional dict from new_weyl_factored_counters().
    Output:
        A tuple (gamma, d_beta, d_gamma), where
        gamma = sigma_alpha(beta), d_beta = dim V_beta, and
        d_gamma = dim V_gamma.
    """
    key = (alpha, beta)
    if key in root_data_cache:
        increment_counter(counters, "root_data_cache_hits")
    else:
        increment_counter(counters, "root_data_cache_misses")
        gamma = G.root_system.reflect_root(alpha, beta)
        root_data_cache[key] = (
            gamma,
            G.root_space_dimension(beta),
            G.root_space_dimension(gamma),
        )
    return root_data_cache[key]


def prune_weyl_matrix_by_root_conjugation(
    G,
    alpha,
    w_alpha,
    w_vars,
    generic_vars,
    root_data_cache,
    counters=None,
):
    """Force Weyl matrix entries to zero using root-conjugation equations.

    Input:
        G: a pinned_group-like object with root_subgroup_map and root data.
        alpha: the root whose Weyl representative is being solved.
        w_alpha: current symbolic Weyl matrix.
        w_vars: current set of symbolic matrix-entry variables.
        generic_vars: symbols treated as generic/non-special parameters.
        root_data_cache: dict used by get_cached_root_data().
        counters: optional dict from new_weyl_factored_counters().
    Output:
        A tuple (w_alpha, w_vars, conjugation_eqs).  The returned w_alpha has
        all variables forced to zero substituted by 0.  The returned w_vars
        removes variables found during the root-conjugation pass.  The final
        entry lists all nonzero entry equations inspected.
    """
    with timed_stage(counters, "time_root_conjugation_pruning_seconds"):
        zero_vars = set()
        conjugation_eqs = []
        for k, beta in enumerate(G.root_system.root_list):
            gamma, d_beta, d_gamma = get_cached_root_data(
                G, alpha, beta, root_data_cache, counters
            )
            assert d_beta == d_gamma
            u = vector_variable(f'u_{k}', d_beta)
            v = vector_variable(f'v_{k}', d_gamma)
            x_beta_u = G.root_subgroup_map(beta, u)
            x_gamma_v = G.root_subgroup_map(gamma, v)
            conjugation_matrix_eq = w_alpha * x_beta_u - x_gamma_v * w_alpha

            for i in range(G.matrix_size):
                for j in range(G.matrix_size):
                    expr = conjugation_matrix_eq[i, j]
                    if not expr.is_zero:
                        conjugation_eqs.append(expr)
                        new_zero_vars = find_zero_vars(
                            expr,
                            w_vars,
                            generic_vars.union(u.free_symbols),
                        )
                        if len(new_zero_vars) >= 1:
                            zero_vars = zero_vars.union(new_zero_vars)
                            w_vars = w_vars - new_zero_vars

        for var in zero_vars:
            w_alpha = w_alpha.subs(var, 0)

    increment_counter(counters, "conjugation_equations", len(conjugation_eqs))
    increment_counter(counters, "conjugation_zero_vars", len(zero_vars))

    return w_alpha, w_vars, conjugation_eqs


def prune_weyl_matrix_by_torus_normalizer(
    G,
    w_alpha,
    w_vars,
    generic_vars,
    t,
    s,
    counters=None,
):
    """Force Weyl matrix entries to zero using torus-normalizer equations.

    Input:
        G: a pinned_group-like object with matrix_size.
        w_alpha: current symbolic Weyl matrix after root-conjugation pruning.
        w_vars: current set of symbolic matrix-entry variables.
        generic_vars: symbols treated as generic/non-special parameters.
        t: generic torus element representing the source torus element.
        s: generic torus element representing the target torus element.
        counters: optional dict from new_weyl_factored_counters().
    Output:
        A tuple (w_alpha, normalizer_eqs).  The returned w_alpha has entries
        forced to zero by w_alpha * t = s * w_alpha substituted by 0.
        normalizer_eqs lists all nonzero entry equations inspected.
    """
    with timed_stage(counters, "time_torus_normalizer_pruning_seconds"):
        zero_vars = set()
        normalizer_matrix_eq = w_alpha * t - s * w_alpha
        normalizer_eqs = []
        for i in range(G.matrix_size):
            for j in range(G.matrix_size):
                expr = normalizer_matrix_eq[i, j]
                if not expr.is_zero:
                    normalizer_eqs.append(expr)
                    new_zero_vars_1 = find_zero_vars(expr, w_vars, generic_vars)
                    new_zero_vars_2 = find_zero_vars(expr, w_vars, s.free_symbols)
                    if len(new_zero_vars_1) >= 1:
                        zero_vars = zero_vars.union(new_zero_vars_1)
                    if len(new_zero_vars_2) >= 1:
                        zero_vars = zero_vars.union(new_zero_vars_2)

        for var in zero_vars:
            w_alpha = w_alpha.subs(var, 0)

    increment_counter(counters, "normalizer_equations", len(normalizer_eqs))
    increment_counter(counters, "normalizer_zero_vars", len(zero_vars))

    return w_alpha, normalizer_eqs


def build_weyl_candidate_dictionary(G, w_alpha, counters=None):
    """Build finite candidate values for the remaining Weyl variables.

    Input:
        G: a pinned_group-like object with matrix_size and optional form data.
        w_alpha: sparse symbolic matrix after zero-forcing.
        counters: optional dict from new_weyl_factored_counters().
    Output:
        A pair (w_alpha, variable_candidate_dict).  In the non-quadratic case,
        w_alpha is the pruned symbolic matrix and each variable gets candidates
        [0, 1, -1].  In the quadratic-extension case, each remaining entry is
        rewritten as x_ij + p_e * y_ij and candidate values are assigned to the
        x/y variables.  Candidate 0 is removed from singleton row/column
        variables by prune_singletons().
    """
    with timed_stage(counters, "time_candidate_dictionary_seconds"):
        w_mask = w_alpha.applyfunc(lambda x: int(x != 0))
        variable_candidate_dict = {}

        if G.form is not None and G.form.primitive_element is not None:
            p_e = G.form.primitive_element
            x_mat = sp.Matrix(
                G.matrix_size,
                G.matrix_size,
                lambda i, j: sp.symbols(f'x_{i}_{j}'),
            )
            y_mat = sp.Matrix(
                G.matrix_size,
                G.matrix_size,
                lambda i, j: sp.symbols(f'y_{i}_{j}'),
            )
            w_alpha = x_mat + p_e * y_mat
            w_alpha = w_alpha.multiply_elementwise(w_mask)
            x_mat = x_mat.multiply_elementwise(w_mask)
            y_mat = y_mat.multiply_elementwise(w_mask)
            x_vars = sorted(x_mat.free_symbols, key=lambda s: s.name)
            y_vars = sorted(y_mat.free_symbols, key=lambda s: s.name)
            for var in x_vars:
                variable_candidate_dict[var] = [0, 1, -1]
            for var in y_vars:
                variable_candidate_dict[var] = [0, 1, -1, 1 / p_e**2, -1 / p_e**2]
        else:
            for var in w_alpha.free_symbols:
                variable_candidate_dict[var] = [0, 1, -1]

        variable_candidate_dict = prune_singletons(w_alpha, variable_candidate_dict)

    increment_counter(counters, "candidate_variables", len(variable_candidate_dict))
    return w_alpha, variable_candidate_dict


def partition_candidate_variables(variable_candidate_dict, counters=None):
    """Split candidate variables by whether zero is still allowed.

    Input:
        variable_candidate_dict: dict mapping symbolic variables to finite
            lists of candidate values.
        counters: optional dict from new_weyl_factored_counters().
    Output:
        A tuple (variables, zero_allowed, zero_forbidden, nonzero_candidates).
        variables is the list of all variables.  zero_allowed contains
        variables where 0 is a candidate.  zero_forbidden contains variables
        where 0 has been pruned.  nonzero_candidates maps every variable to its
        nonzero candidate values.
    """
    variables = list(variable_candidate_dict.keys())
    zero_allowed = [v for v in variables if 0 in variable_candidate_dict[v]]
    zero_forbidden = [v for v in variables if 0 not in variable_candidate_dict[v]]
    nonzero_candidates = {
        v: [c for c in variable_candidate_dict[v] if c != 0]
        for v in variables
    }

    increment_counter(counters, "zero_allowed_variables", len(zero_allowed))
    increment_counter(counters, "zero_forbidden_variables", len(zero_forbidden))

    for v in zero_forbidden:
        if not nonzero_candidates[v]:
            raise ValueError(f"Variable {v} has no valid nonzero candidates")

    return variables, zero_allowed, zero_forbidden, nonzero_candidates


def candidate_belongs_to_rank_one_pattern(G, alpha, candidate, display_extra=False):
    """Check whether a candidate has the expected rank-one subgroup pattern.

    Input:
        G: a pinned_group-like object with compare_subgroup_pattern().
        alpha: the root whose Weyl element is being solved.
        candidate: concrete matrix candidate for w_alpha.
        display_extra: whether to print debugging details.
    Output:
        True if candidate pattern-matches a length-three word in root
        subgroups generated by alpha and -alpha; otherwise False.
    """
    return G.compare_subgroup_pattern(
        matrix_to_test=candidate,
        generating_roots=[alpha, -alpha],
        min_word_length=3,
        max_word_length=3,
        op=operator.le,
        display=display_extra,
    )


def solve_weyl_element_by_candidate_enumeration(
    G,
    alpha,
    w_alpha,
    variable_candidate_dict,
    display_extra=False,
    counters=None,
):
    """Search finite candidate assignments for one Weyl element.

    Input:
        G: a pinned_group-like object with group_constraints and pattern check.
        alpha: the root whose Weyl representative is being solved.
        w_alpha: symbolic matrix after pruning and candidate-variable setup.
        variable_candidate_dict: dict mapping variables to finite candidate
            values.
        display_extra: whether to print detailed search progress.
        counters: optional dict from new_weyl_factored_counters().
    Output:
        A concrete matrix satisfying the group equations and the rank-one
        subgroup pattern check.
    Raises:
        AssertionError if no candidate is found.
    """
    with timed_stage(counters, "time_candidate_enumeration_seconds"):
        group_eqs = G.group_constraints(w_alpha, G.form)
        vanishing_conditions = group_eqs
        min_nonzero = G.matrix_size
        max_nonzero = G.matrix_size
        variables, zero_allowed, zero_forbidden, nonzero_candidates = (
            partition_candidate_variables(variable_candidate_dict, counters)
        )

        forced_count = len(zero_forbidden)
        optional_count = len(zero_allowed)

        if max_nonzero < forced_count:
            raise ValueError(
                f"max_nonzero={G.matrix_size} is less than the number "
                f"of forced nonzeros={forced_count}"
            )
        if max_nonzero > forced_count + optional_count:
            max_nonzero = forced_count + optional_count

        tried = 0
        if display_extra:
            print("\n\n" + "=" * 60 + "\nAttempting brute force solution for w_alpha")
            print("alpha =", alpha)
            print("Variables:", variables)
            print("Candidate dictionary:", variable_candidate_dict)
            print("Variables that can be zero:", zero_allowed)
            print("Variables that can't be zero:", zero_forbidden)
            print("Vanishing conditions:")
            for e in vanishing_conditions:
                sp.pprint(e)

        k_min = max(0, min_nonzero - forced_count)
        k_max = min(optional_count, max_nonzero - forced_count)

        for k in range(k_min, k_max + 1):
            if display_extra:
                print(f"\nTrying combinations with {k} nonzero variables")
                forced_factor = reduce(
                    mul,
                    (len(nonzero_candidates[v]) for v in zero_forbidden),
                    1,
                )
                support_factor = sum(
                    reduce(mul, (len(nonzero_candidates[v]) for v in support), 1)
                    for support in itertools.combinations(zero_allowed, k)
                )
                print("Combinations to try:", support_factor * forced_factor)

            for support in itertools.combinations(zero_allowed, k):
                increment_counter(counters, "supports_tried")
                assignment = {v: 0 for v in zero_allowed if v not in support}
                nz_lists = [nonzero_candidates[v] for v in support]
                forced_lists = [nonzero_candidates[v] for v in zero_forbidden]
                for values in itertools.product(*nz_lists, *forced_lists):
                    split = len(support)
                    assignment.update(dict(zip(support, values[:split])))
                    assignment.update(dict(zip(zero_forbidden, values[split:])))
                    tried += 1
                    increment_counter(counters, "assignments_tried")
                    if display_extra and tried % 10000 == 0:
                        print("Combinations tried:", tried)

                    if all(eq.subs(assignment) == 0 for eq in vanishing_conditions):
                        increment_counter(counters, "group_equation_hits")
                        if display_extra:
                            print("\nBrute force solver found a solution for w_alpha, checking it pattern matches the expected subgroup")
                        candidate = w_alpha.subs(assignment)
                        if candidate_belongs_to_rank_one_pattern(
                            G, alpha, candidate, display_extra
                        ):
                            if display_extra:
                                print("\n\tFound a solution for w_alpha belonging to the right subgroup")
                                print("\talpha = ", alpha)
                                print("\tw_alpha =")
                                sp.pprint(candidate)
                                print("Total combinations tried:", tried)
                                print("=" * 60 + "\n")
                            return candidate
                        increment_counter(counters, "pattern_failures")
                        if display_extra:
                            print("Candidate does not belong to the expected subgroup")

        raise AssertionError(
            f"No solutions for w_alpha for alpha = {alpha} from the group {G.name_string}"
        )


def solve_weyl_element_by_monomial_enumeration(
    G,
    alpha,
    w_alpha,
    variable_candidate_dict,
    display_extra=False,
    counters=None,
):
    """Search candidate assignments using monomial matrix support first.

    Input:
        G: a pinned_group-like object with group_constraints and pattern check.
        alpha: the root whose Weyl representative is being solved.
        w_alpha: symbolic matrix after pruning and candidate-variable setup.
        variable_candidate_dict: dict mapping variables to finite candidate
            values.
        display_extra: whether to print detailed search progress.
        counters: optional dict from new_weyl_factored_counters().
    Output:
        A concrete matrix satisfying the group equations and the rank-one
        subgroup pattern check.
    Raises:
        AssertionError if no monomial-supported candidate is found.

    Difference from solve_weyl_element_by_candidate_enumeration():
        The older brute-force routine chooses exactly matrix_size nonzero
        variables.  This routine chooses exactly one nonzero matrix entry in
        each row and column.  That is the expected shape for elements in the
        normalizer of the diagonal torus, and it also handles quadratic
        extension entries such as x_ij + p_e*y_ij as one matrix position.
    """
    with timed_stage(counters, "time_candidate_enumeration_seconds"):
        group_eqs = G.group_constraints(w_alpha, G.form)
        vanishing_conditions = group_eqs
        variables, zero_allowed, _zero_forbidden, _nonzero_candidates = (
            partition_candidate_variables(variable_candidate_dict, counters)
        )
        variables = sorted(variables, key=lambda s: s.name)
        zero_allowed = set(zero_allowed)
        entry_variables = matrix_entry_variables(w_alpha, variable_candidate_dict)

        if display_extra:
            print("\n\n" + "=" * 60 + "\nAttempting monomial-support solution for w_alpha")
            print("alpha =", alpha)
            print("Variables:", variables)
            print("Candidate dictionary:", variable_candidate_dict)
            print("Entry variables:", entry_variables)
            print("Vanishing conditions:")
            for e in vanishing_conditions:
                sp.pprint(e)

        tried = 0
        for support in enumerate_monomial_entry_supports(
            G.matrix_size,
            entry_variables,
            variable_candidate_dict,
        ):
            increment_counter(counters, "supports_tried")
            increment_counter(counters, "monomial_supports_tried")
            support = set(support)
            selected_vars = sorted(
                {
                    var
                    for pos in support
                    for var in entry_variables[pos]
                },
                key=lambda s: s.name,
            )
            selected_var_set = set(selected_vars)
            zero_vars = [var for var in variables if var not in selected_var_set]

            if any(var not in zero_allowed for var in zero_vars):
                increment_counter(counters, "monomial_supports_rejected")
                continue

            assignment = {var: 0 for var in zero_vars}
            selected_candidate_lists = [
                variable_candidate_dict[var]
                for var in selected_vars
            ]

            for values in itertools.product(*selected_candidate_lists):
                assignment.update(dict(zip(selected_vars, values)))
                tried += 1
                increment_counter(counters, "assignments_tried")
                if display_extra and tried % 10000 == 0:
                    print("Monomial combinations tried:", tried)

                if not all(
                    w_alpha[pos].subs(assignment) != 0
                    for pos in support
                ):
                    increment_counter(counters, "monomial_value_assignments_rejected")
                    continue

                if all(eq.subs(assignment) == 0 for eq in vanishing_conditions):
                    increment_counter(counters, "group_equation_hits")
                    if display_extra:
                        print("\nMonomial solver found a solution for w_alpha, checking it pattern matches the expected subgroup")
                    candidate = w_alpha.subs(assignment)
                    if candidate_belongs_to_rank_one_pattern(
                        G, alpha, candidate, display_extra
                    ):
                        if display_extra:
                            print("\n\tFound a monomial solution for w_alpha belonging to the right subgroup")
                            print("\talpha = ", alpha)
                            print("\tw_alpha =")
                            sp.pprint(candidate)
                            print("Total monomial combinations tried:", tried)
                            print("=" * 60 + "\n")
                        return candidate
                    increment_counter(counters, "pattern_failures")
                    if display_extra:
                        print("Candidate does not belong to the expected subgroup")

        raise AssertionError(
            f"No monomial-supported solutions for w_alpha for alpha = {alpha} "
            f"from the group {G.name_string}"
        )


def solve_one_weyl_element_factored(
    G,
    alpha,
    t,
    s,
    generic_vars,
    root_data_cache,
    display_extra=False,
    counters=None,
    enumeration_method="monomial",
):
    """Run all factored stages for one root alpha.

    Input:
        G: a pinned_group-like object fitted through root subgroup maps.
        alpha: the root whose Weyl representative is being solved.
        t: generic source torus element.
        s: generic target torus element.
        generic_vars: symbols treated as generic/non-special parameters.
        root_data_cache: dict shared across roots for reflected root data.
        display_extra: whether to print detailed search progress.
        counters: optional dict from new_weyl_factored_counters().
        enumeration_method: "monomial" tries the experimental monomial-support
            enumeration with fallback to "brute"; "brute" uses the original
            factored variable-support enumeration directly.
    Output:
        A concrete matrix w_alpha for the requested root.
    """
    increment_counter(counters, "roots_attempted")
    with timed_stage(counters, "time_root_total_seconds"):
        w_alpha, w_vars = initialize_symbolic_weyl_matrix(G, counters)
        w_alpha, w_vars, _conjugation_eqs = prune_weyl_matrix_by_root_conjugation(
            G,
            alpha,
            w_alpha,
            w_vars,
            generic_vars,
            root_data_cache,
            counters,
        )
        w_alpha, _normalizer_eqs = prune_weyl_matrix_by_torus_normalizer(
            G,
            w_alpha,
            w_vars,
            generic_vars,
            t,
            s,
            counters,
        )
        w_alpha, variable_candidate_dict = build_weyl_candidate_dictionary(
            G, w_alpha, counters
        )
        if enumeration_method == "monomial":
            try:
                result = solve_weyl_element_by_monomial_enumeration(
                    G,
                    alpha,
                    w_alpha,
                    variable_candidate_dict,
                    display_extra,
                    counters,
                )
            except AssertionError:
                increment_counter(counters, "brute_force_fallbacks")
                result = solve_weyl_element_by_candidate_enumeration(
                    G,
                    alpha,
                    w_alpha,
                    variable_candidate_dict,
                    display_extra,
                    counters,
                )
        elif enumeration_method == "brute":
            result = solve_weyl_element_by_candidate_enumeration(
                G,
                alpha,
                w_alpha,
                variable_candidate_dict,
                display_extra,
                counters,
            )
        else:
            raise ValueError(f"Unknown Weyl enumeration method: {enumeration_method}")
    increment_counter(counters, "roots_solved")
    return result


def fit_weyl_group_elements_factored(
    G,
    display=True,
    display_extra=False,
    enumeration_method="monomial",
):
    """Fit all Weyl elements using the external factored brute-force solver.

    Input:
        G: a pinned_group-like object already fitted through root systems,
            root spaces, root subgroup maps, homomorphism defect coefficients,
            and commutator coefficients.
        display: whether to print high-level progress.
        display_extra: whether to print detailed brute-force search progress.
        enumeration_method: "monomial" tries the experimental monomial-support
            enumeration with fallback to "brute"; "brute" uses the original
            factored variable-support enumeration.
    Output:
        None. Mutates G by installing G.torus_reflection_map,
        G.weyl_element_list, and G.weyl_element_map.
    """
    counters = new_weyl_factored_counters()
    G.weyl_factored_counters = counters

    with timed_stage(counters, "time_total_seconds"):
        fit_torus_reflection_map(G, display, counters)
        if display:
            print(f"Fitting Weyl elements (w_α) with factored {enumeration_method} solver")

        G.weyl_element_list = {}
        t, s, generic_vars = get_generic_weyl_context(G, counters)
        root_data_cache = {}

        for alpha in G.root_system.root_list:
            G.weyl_element_list[alpha] = solve_one_weyl_element_factored(
                G,
                alpha,
                t,
                s,
                generic_vars,
                root_data_cache,
                display_extra,
                counters,
                enumeration_method,
            )

        increment_counter(counters, "roots_installed", len(G.weyl_element_list))

        def wem(alpha):
            return G.weyl_element_list[alpha]

        G.weyl_element_map = wem

    if display:
        print_weyl_factored_counters(counters)


################################################################################
### Helper utilities
################################################################################
#
# These helpers are kept at the bottom because they are generic instrumentation
# utilities rather than mathematical stages of the Weyl element algorithm.  In a
# larger cleanup, they could move to a small shared counters/timing library.


def new_weyl_factored_counters():
    """Create counters for the factored brute-force Weyl solver.

    Input:
        None.
    Output:
        A dictionary containing integer counters and wall-clock timing fields.
        The dictionary is intentionally plain so it can be attached to a
        pinned_group object and inspected interactively.
    """
    return {
        "roots_attempted": 0,
        "roots_solved": 0,
        "roots_installed": 0,
        "root_data_cache_hits": 0,
        "root_data_cache_misses": 0,
        "conjugation_equations": 0,
        "conjugation_zero_vars": 0,
        "normalizer_equations": 0,
        "normalizer_zero_vars": 0,
        "candidate_variables": 0,
        "zero_allowed_variables": 0,
        "zero_forbidden_variables": 0,
        "supports_tried": 0,
        "monomial_supports_tried": 0,
        "monomial_supports_rejected": 0,
        "assignments_tried": 0,
        "monomial_value_assignments_rejected": 0,
        "group_equation_hits": 0,
        "pattern_failures": 0,
        "brute_force_fallbacks": 0,
        "time_total_seconds": 0.0,
        "time_torus_reflections_seconds": 0.0,
        "time_generic_context_seconds": 0.0,
        "time_root_total_seconds": 0.0,
        "time_symbolic_initialization_seconds": 0.0,
        "time_root_conjugation_pruning_seconds": 0.0,
        "time_torus_normalizer_pruning_seconds": 0.0,
        "time_candidate_dictionary_seconds": 0.0,
        "time_candidate_enumeration_seconds": 0.0,
    }


def increment_counter(counters, key, amount=1):
    """Increment one factored Weyl counter when counters are provided.

    Input:
        counters: a dict from new_weyl_factored_counters(), or None.
        key: counter name.
        amount: integer amount to add.
    Output:
        None. Mutates counters when counters is not None.
    """
    if counters is not None:
        counters[key] += amount


def matrix_entry_variables(w_alpha, variable_candidate_dict):
    """Return candidate variables attached to each possibly nonzero entry.

    Input:
        w_alpha: symbolic Weyl matrix after candidate construction.
        variable_candidate_dict: dict mapping candidate variables to values.
    Output:
        A dict keyed by matrix position (i, j).  The value is the list of
        candidate variables appearing in that entry.  Constant nonzero entries
        are retained with an empty variable list because a monomial support
        cannot turn them off.
    """
    candidate_vars = set(variable_candidate_dict)
    entry_vars = {}
    for i in range(w_alpha.rows):
        for j in range(w_alpha.cols):
            expr = w_alpha[i, j]
            if expr == 0:
                continue
            vars_in_entry = sorted(
                expr.free_symbols.intersection(candidate_vars),
                key=lambda s: s.name,
            )
            entry_vars[(i, j)] = vars_in_entry
    return entry_vars


def enumerate_monomial_entry_supports(matrix_size, entry_variables, variable_candidate_dict):
    """Yield entry supports with one selected position in each row and column.

    Input:
        matrix_size: size n of the n x n Weyl matrix.
        entry_variables: dict from matrix_entry_variables().
        variable_candidate_dict: dict mapping candidate variables to values.
    Output:
        Iterator of tuples of matrix positions.  Each tuple has length n and
        uses every row and every column exactly once.  Positions containing a
        variable whose candidate list forbids 0 are treated as forced.
    """
    positions_by_row = {i: [] for i in range(matrix_size)}
    forced_positions = set()

    for pos, vars_in_entry in entry_variables.items():
        row, _col = pos
        positions_by_row[row].append(pos)
        if any(0 not in variable_candidate_dict[var] for var in vars_in_entry):
            forced_positions.add(pos)

    forced_rows = {}
    forced_cols = {}
    for row, col in forced_positions:
        if row in forced_rows and forced_rows[row] != (row, col):
            return
        if col in forced_cols and forced_cols[col] != (row, col):
            return
        forced_rows[row] = (row, col)
        forced_cols[col] = (row, col)

    rows_by_branching = sorted(
        range(matrix_size),
        key=lambda row: len(positions_by_row[row]),
    )

    def search(row_index, used_cols, support):
        if row_index == len(rows_by_branching):
            yield tuple(support)
            return

        row = rows_by_branching[row_index]
        if row in forced_rows:
            choices = [forced_rows[row]]
        else:
            choices = positions_by_row[row]

        for pos in choices:
            _row, col = pos
            if col in used_cols:
                continue
            if col in forced_cols and forced_cols[col] != pos:
                continue
            yield from search(row_index + 1, used_cols.union({col}), support + [pos])

    yield from search(0, set(), [])


def add_elapsed_time(counters, key, elapsed_seconds):
    """Add elapsed time to one factored Weyl timing counter.

    Input:
        counters: a dict from new_weyl_factored_counters(), or None.
        key: timing counter name.
        elapsed_seconds: float number of seconds to add.
    Output:
        None. Mutates counters when counters is not None.
    """
    if counters is not None:
        counters[key] += elapsed_seconds


@contextmanager
def timed_stage(counters, key):
    """Measure one stage and add elapsed wall-clock time to counters.

    Input:
        counters: a dict from new_weyl_factored_counters(), or None.
        key: timing counter name.
    Output:
        Context manager that records elapsed time on exit.
    """
    start = time.perf_counter()
    try:
        yield
    finally:
        add_elapsed_time(counters, key, time.perf_counter() - start)


def print_weyl_factored_counters(counters):
    """Print a summary of factored Weyl solver counters and timings.

    Input:
        counters: a dict from new_weyl_factored_counters().
    Output:
        None. Prints a human-readable summary.
    """
    print("Factored brute-force Weyl counters:")
    for key in (
        "roots_attempted",
        "roots_solved",
        "roots_installed",
        "root_data_cache_hits",
        "root_data_cache_misses",
        "conjugation_equations",
        "conjugation_zero_vars",
        "normalizer_equations",
        "normalizer_zero_vars",
        "candidate_variables",
        "zero_allowed_variables",
        "zero_forbidden_variables",
        "supports_tried",
        "monomial_supports_tried",
        "monomial_supports_rejected",
        "assignments_tried",
        "monomial_value_assignments_rejected",
        "group_equation_hits",
        "pattern_failures",
        "brute_force_fallbacks",
    ):
        print(f"\t{key}: {counters[key]}")

    print("Factored brute-force Weyl timing:")
    for key in (
        "time_total_seconds",
        "time_torus_reflections_seconds",
        "time_generic_context_seconds",
        "time_root_total_seconds",
        "time_symbolic_initialization_seconds",
        "time_root_conjugation_pruning_seconds",
        "time_torus_normalizer_pruning_seconds",
        "time_candidate_dictionary_seconds",
        "time_candidate_enumeration_seconds",
    ):
        print(f"\t{key}: {counters[key]:.4f}")
